/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo1.asreliquiasmatematicas.ui;

import com.grupo1.asreliquiasmatematicas.Dialogos;


public class TelaNorte extends javax.swing.JFrame {
    Dialogos dialogos = new Dialogos();
    int dialogoAtual = -1;

    private void proximoDialogo() {
        dialogoAtual++;
        if (dialogoAtual == dialogos.norte.length) {
            pnDialogo.setVisible(false);
            pnQuiz.setVisible(true);
        } else {
            cxDialogo.setText(dialogos.norte[dialogoAtual]);
        }
    }

    public TelaNorte() {
        initComponents();
        pnQuiz.setVisible(false);
        proximoDialogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnQuiz = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnDialogo = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        cxDialogo = new javax.swing.JTextArea();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnQuiz.setOpaque(false);

        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout pnQuizLayout = new javax.swing.GroupLayout(pnQuiz);
        pnQuiz.setLayout(pnQuizLayout);
        pnQuizLayout.setHorizontalGroup(
            pnQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnQuizLayout.createSequentialGroup()
                    .addGap(0, 367, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 368, Short.MAX_VALUE)))
        );
        pnQuizLayout.setVerticalGroup(
            pnQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(pnQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnQuizLayout.createSequentialGroup()
                    .addGap(0, 117, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 117, Short.MAX_VALUE)))
        );

        getContentPane().add(pnQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 250));

        pnDialogo.setOpaque(false);

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        cxDialogo.setEditable(false);
        cxDialogo.setBackground(new java.awt.Color(0, 0, 0));
        cxDialogo.setColumns(20);
        cxDialogo.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        cxDialogo.setForeground(new java.awt.Color(255, 255, 51));
        cxDialogo.setLineWrap(true);
        cxDialogo.setRows(5);
        cxDialogo.setText("text");
        cxDialogo.setWrapStyleWord(true);
        cxDialogo.setOpaque(false);

        javax.swing.GroupLayout pnDialogoLayout = new javax.swing.GroupLayout(pnDialogo);
        pnDialogo.setLayout(pnDialogoLayout);
        pnDialogoLayout.setHorizontalGroup(
            pnDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDialogoLayout.createSequentialGroup()
                .addGap(0, 705, Short.MAX_VALUE)
                .addComponent(btnNext))
            .addGroup(pnDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDialogoLayout.createSequentialGroup()
                    .addContainerGap(10, Short.MAX_VALUE)
                    .addComponent(cxDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnDialogoLayout.setVerticalGroup(
            pnDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDialogoLayout.createSequentialGroup()
                .addComponent(btnNext)
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(pnDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDialogoLayout.createSequentialGroup()
                    .addContainerGap(48, Short.MAX_VALUE)
                    .addComponent(cxDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(pnDialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 780, 160));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reino Norte.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(819, 600));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        proximoDialogo();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNorte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnNext;
    private javax.swing.JTextArea cxDialogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnDialogo;
    private javax.swing.JPanel pnQuiz;
    // End of variables declaration//GEN-END:variables
}
